### ISSUE TITLE
Data Request from LDC

### ISSUE THREAD

**Issue by BaiYunpeng1949** [berzak/celer#1]
Hi, thank you for the useful repo for data request!

Do I need to pay for a request for the corpus you mentioned?

I moved the README.doc (from Online Documentation: LDC95T7 Documents) and README.2nd (from Online Documentation: LDC2000T43 Documents) to the obtain_data.py, but still cannot download.

I checked onlin some guys said [ref](https://www.reddit.com/r/LanguageTechnology/comments/wezv1z/how_to_download_a_dataset_from_ldc/) there should be a Request Data button on the bottom of the page, but I did not see it (though my institute should be legible).

![image](https://github.com/user-attachments/assets/f4fc8377-dcd7-4bd1-925b-cd8e63bfecf2)
![image](https://github.com/user-attachments/assets/513fa7cf-aef4-484e-9fb4-632ea5184178)

![image](https://github.com/user-attachments/assets/735f812b-ba68-4c8f-bc30-08de26b5beba)
![image](https://github.com/user-attachments/assets/1ccbc5b2-da9b-4522-aac5-cdda3384ae41)

Do you have any clue?

Thanks!

**Comment by berzak** [comment]
Hi,

Yes, you need to obtain these two datasets first. This is typically done through a subscription to LDC (which indeed has fees). Try to check if you lab/department/university has such a subscription.

Best,
Yevgeni
